quarkus.http.port=8080
quarkus.application.name=rep-control-backend

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:mysql://localhost:3306/rep_equipos_apilamiento}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:root}

quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-at-migrate=true
quarkus.flyway.locations=db/migration

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
