CREATE TABLE roles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255) NULL,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NULL,
    fecha_baja DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_rol_nombre (nombre)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sitios (
    id BIGINT NOT NULL AUTO_INCREMENT,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500) NULL,
    direccion VARCHAR(500) NULL,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NULL,
    fecha_baja DATETIME NULL,
    usuario_creacion BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_sitio_codigo (codigo),
    INDEX idx_sitio_nombre (nombre)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE usuarios (
    id BIGINT NOT NULL AUTO_INCREMENT,
    id_microsoft VARCHAR(255) NOT NULL,
    correo VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    puesto VARCHAR(255) NULL,
    area VARCHAR(255) NULL,
    empresa VARCHAR(255) NULL,
    departamento VARCHAR(255) NULL,
    ubicacion VARCHAR(255) NULL,
    rol_id BIGINT NOT NULL,
    sitio_id BIGINT NULL,
    ultimo_acceso DATETIME NULL,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NULL,
    fecha_baja DATETIME NULL,
    usuario_creacion BIGINT NOT NULL,
    usuario_actualizacion BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_usuario_correo (correo),
    UNIQUE INDEX idx_usuario_microsoft (id_microsoft),
    INDEX idx_usuario_rol (rol_id),
    INDEX idx_usuario_sitio (sitio_id),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES roles(id),
    CONSTRAINT fk_usuario_sitio FOREIGN KEY (sitio_id) REFERENCES sitios(id),
    CONSTRAINT fk_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE campanas (
    id BIGINT NOT NULL AUTO_INCREMENT,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    sitio_id BIGINT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'ACTIVA',
    es_activa TINYINT(1) NOT NULL DEFAULT 0,
    descripcion VARCHAR(500) NULL,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NULL,
    fecha_baja DATETIME NULL,
    usuario_creacion BIGINT NOT NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_campana_codigo (codigo),
    INDEX idx_campana_sitio (sitio_id),
    INDEX idx_campana_estado (estado),
    INDEX idx_campana_activa (es_activa),
    CONSTRAINT fk_campana_sitio FOREIGN KEY (sitio_id) REFERENCES sitios(id),
    CONSTRAINT fk_campana_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
