CREATE TABLE psr (
    id BIGINT NOT NULL AUTO_INCREMENT,
    numero VARCHAR(50) NOT NULL,
    campana_id BIGINT NOT NULL,
    sitio_id BIGINT NOT NULL,
    motivo_id BIGINT NOT NULL,
    descripcion TEXT NULL,
    fecha_solicitud DATE NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'ACTIVO',
    observaciones TEXT NULL,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NULL,
    usuario_creacion BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_psr_numero (numero),
    INDEX idx_psr_campana (campana_id),
    INDEX idx_psr_sitio (sitio_id),
    INDEX idx_psr_estado (estado),
    CONSTRAINT fk_psr_campana FOREIGN KEY (campana_id) REFERENCES campanas(id),
    CONSTRAINT fk_psr_sitio FOREIGN KEY (sitio_id) REFERENCES sitios(id),
    CONSTRAINT fk_psr_motivo FOREIGN KEY (motivo_id) REFERENCES motivos_psr(id),
    CONSTRAINT fk_psr_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE osr (
    id BIGINT NOT NULL AUTO_INCREMENT,
    numero VARCHAR(50) NOT NULL,
    psr_id BIGINT NOT NULL,
    equipo_id BIGINT NULL,
    fecha_asignacion DATE NOT NULL,
    hora_inicio TIME NULL,
    hora_fin TIME NULL,
    horometro_inicio DECIMAL(10,2) NULL,
    horometro_fin DECIMAL(10,2) NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE',
    observaciones TEXT NULL,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NULL,
    usuario_creacion BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_osr_numero (numero),
    INDEX idx_osr_psr (psr_id),
    INDEX idx_osr_equipo (equipo_id),
    CONSTRAINT fk_osr_psr FOREIGN KEY (psr_id) REFERENCES psr(id),
    CONSTRAINT fk_osr_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE equipos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    codigo VARCHAR(50) NOT NULL,
    numero_serie VARCHAR(100) NOT NULL,
    marca VARCHAR(100) NULL,
    modelo VARCHAR(100) NULL,
    campana_id BIGINT NULL,
    osr_id BIGINT NULL,
    proveedor_id BIGINT NOT NULL,
    tipo_equipo_id BIGINT NOT NULL,
    marca_id BIGINT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'DISPONIBLE',
    bateria_tipo VARCHAR(50) NULL,
    bateria_horas DECIMAL(5,2) NULL,
    bateria_voltaje VARCHAR(20) NULL,
    cargador_info VARCHAR(255) NULL,
    transformador_info VARCHAR(255) NULL,
    fecha_ingreso DATE NULL,
    fecha_devolucion DATE NULL,
    horometro_actual DECIMAL(10,2) NULL,
    observaciones TEXT NULL,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NULL,
    fecha_baja DATETIME NULL,
    usuario_creacion BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_equipo_codigo (codigo),
    INDEX idx_equipo_serie (numero_serie),
    INDEX idx_equipo_campana (campana_id),
    INDEX idx_equipo_proveedor (proveedor_id),
    INDEX idx_equipo_tipo (tipo_equipo_id),
    INDEX idx_equipo_estado (estado),
    INDEX idx_equipo_osr (osr_id),
    CONSTRAINT fk_equipo_campana FOREIGN KEY (campana_id) REFERENCES campanas(id),
    CONSTRAINT fk_equipo_osr FOREIGN KEY (osr_id) REFERENCES osr(id),
    CONSTRAINT fk_equipo_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id),
    CONSTRAINT fk_equipo_tipo_equipo FOREIGN KEY (tipo_equipo_id) REFERENCES tipos_equipos(id),
    CONSTRAINT fk_equipo_marca FOREIGN KEY (marca_id) REFERENCES marcas(id),
    CONSTRAINT fk_equipo_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE osr ADD CONSTRAINT fk_osr_equipo FOREIGN KEY (equipo_id) REFERENCES equipos(id);

CREATE TABLE equipos_campanias_historial (
    id BIGINT NOT NULL AUTO_INCREMENT,
    equipo_id BIGINT NOT NULL,
    campana_id BIGINT NOT NULL,
    fecha_inicio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin DATETIME NULL,
    motivo VARCHAR(255) NULL,
    usuario_creacion BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_equipo_campana_hist_equipo (equipo_id),
    INDEX idx_equipo_campana_hist_campana (campana_id),
    INDEX idx_equipo_campana_hist_fecha_inicio (fecha_inicio),
    CONSTRAINT fk_equipo_campana_hist_equipo FOREIGN KEY (equipo_id) REFERENCES equipos(id),
    CONSTRAINT fk_equipo_campana_hist_campana FOREIGN KEY (campana_id) REFERENCES campanas(id),
    CONSTRAINT fk_equipo_campana_hist_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE averias (
    id BIGINT NOT NULL AUTO_INCREMENT,
    codigo VARCHAR(50) NOT NULL,
    equipo_id BIGINT NOT NULL,
    tipo_averia_id BIGINT NOT NULL,
    estado_averia_id BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL,
    descripcion_falla TEXT NOT NULL,
    descripcion_atencion TEXT NULL,
    accion_correctiva TEXT NULL,
    fecha_reporte DATETIME NOT NULL,
    fecha_atencion DATETIME NULL,
    fecha_cierre DATETIME NULL,
    horas_inactivo DECIMAL(10,2) NULL,
    usuario_reporta_id BIGINT NOT NULL,
    usuario_atiende_id BIGINT NULL,
    observaciones TEXT NULL,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NULL,
    usuario_creacion BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_averia_codigo (codigo),
    INDEX idx_averia_equipo (equipo_id),
    INDEX idx_averia_tipo (tipo_averia_id),
    INDEX idx_averia_estado (estado_averia_id),
    INDEX idx_averia_fecha (fecha_reporte),
    INDEX idx_averia_proveedor (proveedor_id),
    CONSTRAINT fk_averia_equipo FOREIGN KEY (equipo_id) REFERENCES equipos(id),
    CONSTRAINT fk_averia_tipo_averia FOREIGN KEY (tipo_averia_id) REFERENCES tipos_averias(id),
    CONSTRAINT fk_averia_estado_averia FOREIGN KEY (estado_averia_id) REFERENCES estados_averias(id),
    CONSTRAINT fk_averia_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id),
    CONSTRAINT fk_averia_usuario_reporta FOREIGN KEY (usuario_reporta_id) REFERENCES usuarios(id),
    CONSTRAINT fk_averia_usuario_atiende FOREIGN KEY (usuario_atiende_id) REFERENCES usuarios(id),
    CONSTRAINT fk_averia_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE evidencias (
    id BIGINT NOT NULL AUTO_INCREMENT,
    equipo_id BIGINT NULL,
    averia_id BIGINT NULL,
    osr_id BIGINT NULL,
    tipo VARCHAR(50) NOT NULL,
    nombre_original VARCHAR(255) NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    ruta VARCHAR(500) NOT NULL,
    tamano INT NOT NULL,
    ancho INT NULL,
    alto INT NULL,
    formato VARCHAR(20) NOT NULL,
    descripcion VARCHAR(255) NULL,
    usuario_id BIGINT NOT NULL,
    fecha_carga DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_baja DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_evidencia_equipo (equipo_id),
    INDEX idx_evidencia_averia (averia_id),
    INDEX idx_evidencia_osr (osr_id),
    INDEX idx_evidencia_tipo (tipo),
    INDEX idx_evidencia_fecha (fecha_carga),
    CONSTRAINT fk_evidencia_equipo FOREIGN KEY (equipo_id) REFERENCES equipos(id),
    CONSTRAINT fk_evidencia_averia FOREIGN KEY (averia_id) REFERENCES averias(id),
    CONSTRAINT fk_evidencia_osr FOREIGN KEY (osr_id) REFERENCES osr(id),
    CONSTRAINT fk_evidencia_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
