quarkus.http.port=8080
quarkus.application.name=rep-control-backend

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:mysql://localhost:3307/rep_equipos_apilamiento}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:root}

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.hibernate-orm.log.sql=false
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-on-migrate=true
quarkus.flyway.locations=db/migration

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:8081}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] %s%e%n

mp.jwt.verify.issuer=${JWT_ISSUER:https://repcontrol.pe}
mp.jwt.verify.secretkey=${JWT_SECRET:OXY8p2u8JcvWsGy7Gp5TYzdp7tEFfHXSzaqPU6J3t3M=}
smallrye.jwt.new-token.signature-algorithm=HS256
smallrye.jwt.new-token.issuer=${JWT_ISSUER:https://repcontrol.pe}
smallrye.jwt.new-token.lifespan=900
smallrye.jwt.new-token.refresh-lifespan=86400

# Microsoft Entra ID (Azure AD)
microsoft.tenant.id=${MICROSOFT_TENANT_ID:04e05ea3-3981-4a7b-9be2-17535cf34b8f}
microsoft.client.id=${MICROSOFT_CLIENT_ID:2953b82b-0891-41d0-99ec-6d2951f46851}

quarkus.http.auth.permission.authenticated.paths=/api/v1/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.auth.permission.authenticated.methods=GET,POST,PUT,DELETE
quarkus.http.limits.max-body-size=${MAX_BODY_SIZE:5M}

quarkus.http.auth.permission.public.paths=/api/v1/auth/login,/api/v1/auth/refresh,/q/health,/openapi,/swagger/*
quarkus.http.auth.permission.public.policy=permit
